export type PortfolioKind = 'photo' | 'video';
export type PortfolioAsset = { title: string; kind: PortfolioKind; year: string; location: string; summary: string; asset: string; poster?: string; };
export const portfolioAssets: PortfolioAsset[] = [
{ title: '20240321 191038',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240321_191038.jpg',
  },
{ title: '20240819 002314',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240819_002314.jpg',
  },
{ title: '20240819 002320',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240819_002320.jpg',
  },
{ title: '20240819 002329',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240819_002329.jpg',
  },
{ title: '20240819 002335',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240819_002335.jpg',
  },
{ title: '20240819 002346',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240819_002346.jpg',
  },
{ title: '20240819 002528 In',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240819_002528_In.jpg',
  },
{ title: '20240819 002613',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20240819_002613.jpg',
  },
{ title: '20250531 191150',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/20250531_191150.jpg',
  },
{ title: '6',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/6.jpg',
  },
{ title: 'PH1',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH1.jpg',
  },
{ title: 'PH10',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH10.jpg',
  },
{ title: 'PH11',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH11.jpg',
  },
{ title: 'PH12',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH12.jpg',
  },
{ title: 'PH13',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH13.jpg',
  },
{ title: 'PH14',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH14.jpg',
  },
{ title: 'PH15',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH15.jpg',
  },
{ title: 'PH2',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH2.jpg',
  },
{ title: 'PH3',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH3.jpg',
  },
{ title: 'PH4',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH4.jpg',
  },
{ title: 'PH5',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH5.jpg',
  },
{ title: 'PH6',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH6.jpg',
  },
{ title: 'PH7',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH7.jpg',
  },
{ title: 'PH8',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH8.jpg',
  },
{ title: 'PH9',
  kind: 'photo',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/image/upload/v1789235623/PH9.jpg',
  },
{ title: 'AMNM QND V1 1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/AMNM_QND_V1-1.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/AMNM_QND_V1_1.jpg'
  },
{ title: 'BEAT TEASER 1 FINAL 1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/BEAT%20TEASER%201%20FINAL%201.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/BEAT_TEASER_1_FINAL_1.jpg'
  },
{ title: 'Barber Bay V2.1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Barber%20Bay%20V2.1.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Barber_Bay_V2_1.jpg'
  },
{ title: 'CQ1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/CQ1.mov',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/CQ1.jpg'
  },
{ title: 'Car wrap defender',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Car%20wrap%20defender.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Car_wrap_defender.jpg'
  },
{ title: 'Clements Work Process ',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Clements%20Work%20Process%20.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Clements_Work_Process_.jpg'
  },
{ title: 'Coffee and Sweet V3',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Coffee_and_Sweet_V3.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Coffee_and_Sweet_V3.jpg'
  },
{ title: 'Djezzy Commercial 1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Djezzy%20Commercial%201.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Djezzy_Commercial_1.jpg'
  },
{ title: 'Editorial video 2 Female  Frames',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Editorial_video_2_Female__Frames.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Editorial_video_2_Female_Frames.jpg'
  },
{ title: 'Editorial video 6 (Male)  Frames',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Editorial_video_6_(Male)__Frames.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Editorial_video_6_Male_Frames.jpg'
  },
{ title: 'FANCY SPEED RAMP 12 (1)',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/FANCY_SPEED_RAMP_12_(1).mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/FANCY_SPEED_RAMP_12_1_.jpg'
  },
{ title: 'FTV 8',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/FTV%208.mov',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/FTV_8.jpg'
  },
{ title: 'Fabios Documentary',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Fabios%20Documentary.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Fabios_Documentary.jpg'
  },
{ title: 'Frames Brett',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Frames_Brett.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Frames_Brett.jpg'
  },
{ title: 'Frames v03',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Frames_v03.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Frames_v03.jpg'
  },
{ title: 'FsRT Video',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/FsRT%20Video.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/FsRT_Video.jpg'
  },
{ title: 'Gharrafa Stat Ad',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Gharrafa%20Stat%20Ad.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Gharrafa_Stat_Ad.jpg'
  },
{ title: 'Hamoud boualem Ad 1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Hamoud%20boualem%20Ad%201.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Hamoud_boualem_Ad_1.jpg'
  },
{ title: 'Hamoud boualem ad 2',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Hamoud%20boualem%20ad%202.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Hamoud_boualem_ad_2.jpg'
  },
{ title: 'Hamoud boualem ad 3',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Hamoud%20boualem%20ad%203.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Hamoud_boualem_ad_3.jpg'
  },
{ title: 'Horati Sahlep',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Horati_Sahlep.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Horati_Sahlep.jpg'
  },
{ title: 'IMG 2517',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/IMG_2517.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/IMG_2517.jpg'
  },
{ title: 'MOGOBOGO reel (v2)',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/MOGOBOGO%20reel%20(v2).mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/MOGOBOGO_reel_v2_.jpg'
  },
{ title: 'Night vibes with Football  Ottoman',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Night%20vibes%20with%20Football_%20Ottoman.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Night_vibes_with_Football_Ottoman.jpg'
  },
{ title: 'OMO ad ',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/OMO%20ad%20.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/OMO_ad_.jpg'
  },
{ title: 'Ram Vibes 2 v2',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Ram%20Vibes%202%20v2.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Ram_Vibes_2_v2.jpg'
  },
{ title: 'Store Highlight (V1)',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Store%20Highlight%20(V1).mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Store_Highlight_V1_.jpg'
  },
{ title: 'The Closet   Chic ',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/The_Closet_-_Chic_.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/The_Closet_Chic_.jpg'
  },
{ title: 'This is Ottoman',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/This_is_Ottoman.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/This_is_Ottoman.jpg'
  },
{ title: 'Top Sports Match',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Top_Sports_Match.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Top_Sports_Match.jpg'
  },
{ title: 'Video Idea 4',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/Video%20Idea%204.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/Video_Idea_4.jpg'
  },
{ title: 'crosswalk',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/crosswalk.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/crosswalk.jpg'
  },
{ title: 'model 1 video 1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/model_1_video_1.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/model_1_video_1.jpg'
  },
{ title: 'model 2 video 1',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/model_2_video_1.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/model_2_video_1.jpg'
  },
{ title: 'ottoman mw',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/ottoman_mw.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/ottoman_mw.jpg'
  },
{ title: 'the closet factory',
  kind: 'video',
  year: '2025',
  location: 'Portfolio',
  summary: 'Portfolio work',
  asset: 'https://res.cloudinary.com/zsyvfq70/video/upload/the_closet_factory.mp4',
  poster: 'https://res.cloudinary.com/zsyvfq70/video/upload/h_250,q_auto/the_closet_factory.jpg'
  },
];
